### ISSUE TITLE
About depth ranges

### ISSUE THREAD

**Issue by Xusyy** [SeasonDepth/SeasonDepth#11]
Thank you for your great work!
I am quite confused about the depth range of SeasonDepth. Is there a maximun or minimun depth value to restrict my prediction? 
Plus, what is the measurement (m, cm, mm...) of the gt depth value?
Apologies if I missed that information in your paper.

**Comment by yangbaoquan** [comment]
It should be noted that gt of SeasonDepth is realtive range. That means you could not use it directly as absolute depth map to either train or evaluate a model. Actually, we mentioned it in our paper about how to align a predicted depth map with gt.

I hope that can help you.
