### ISSUE TITLE
Image undistortion for "SeasonDepth_trainingset_v1.1/slice4"

### ISSUE THREAD

**Issue by jaehyuck0103** [SeasonDepth/SeasonDepth#15]
Unlike other sequences, it seems that the intrinsic undistortion is not applied to "SeasonDepth_trainingset_v1.1/slice4".
Could you update the dataset as an undistorted one?

**Comment by SeasonDepth** [comment]
Sorry for the late reply, and we will update it ASAP. @yangbaoquan
