### ISSUE TITLE
directory structure of test dataset

### ISSUE THREAD

**Issue by xjixzz** [SeasonDepth/SeasonDepth#5]
i have downloaded the  test dataset of seasondepth but found that the directory structure of the  testset is not the same as suggested by the evaluation code.  The validation dataset are split by environments while the evalution code assumes the dataset are split by slices. Can you provide the testset split by slices or other solutions?
Thank you!

**Comment by yangbaoquan** [comment]
Thank you for focusing on our work.
Actually, the test set is from slice9 of [Extended-CMU-Seasons](https://data.ciirc.cvut.cz/public/projects/2020VisualLocalization/Extended-CMU-Seasons/), so you are suggested to generate predicted depth maps of rgb images in test set and put them in `$TESTSET_DIR/depth/slice9`.
As for the validation set, you can just simply consider it as one slice, slice2 for example, and put the predicted depth maps in `$VALIDATIONSET_DIR/predicted/slice2`. Then you are able to evaluate them totally. Please remember to move all images from `$VALIDATIONSET_DIR/depth/env*/c*/*.png` to `$VALIDATIONSET_DIR/depth/slice2/*.png`
Split of slices is not that necessary while carrying out evaluation.
Hope that can help you.

**Comment by xjixzz** [comment]
Your reply really helped me, thank you!
