### ISSUE TITLE
Submitting time

### ISSUE THREAD

**Issue by waterbearbee** [SeasonDepth/SeasonDepth#8]
When can we submit the prediction results? We have send the predicted depth maps to the email (seasondepth@outlook.com), but there is no reply.

**Comment by SeasonDepth** [comment]
Thanks for your interest. We have checked the email inbox but have not found any zip submission yet. How about sending to the email again and cc'ing to hanjianghu@cmu.edu and yangbaoquan@sjtu.edu.cn? We will double-check what happened and give your evaluation result ASAP. And the automatic submission will be online before the end of this month, really sorry for the inconvenience.
