### ISSUE TITLE
How do I use the evaluation file

### ISSUE THREAD

**Issue by linxcan** [SeasonDepth/SeasonDepth#9]
I see the path used for evaluation from GitHub as follows, but the file directories of the test set I downloaded are not the same, how do I use the evaluation file?
![image](https://user-images.githubusercontent.com/91445884/164651972-0f544b51-4ee5-4ea4-8ae9-e9f64972855a.png)

The directories of the downloaded test set are as follows：seasontest\env00\c0\*.jpg.

**Comment by yangbaoquan** [comment]
Hello，maybe my reply in #5 can help you.

**Comment by linxcan** [comment]
Your reply really helped me, thank you!
